// <auto-generated />
using System;
using AguiarPay.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AguiarPay.Data.Migrations
{
    [DbContext(typeof(AguiarDbContext))]
    [Migration("20211106014930_Melhoria2")]
    partial class Melhoria2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AguiarPay.Business.Models.ComandaColetiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ComandasColetivas");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.ComandaIndividual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ComandasIndividuais");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.PedidoColetivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComandaColetivaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComandaColetivaId")
                        .IsUnique();

                    b.ToTable("PedidosColetivos");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.PedidoIndividual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComandaIndividualId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComandaIndividualId")
                        .IsUnique();

                    b.ToTable("PedidosIndividuais");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PedidoColetivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoIndividualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoColetivoId");

                    b.HasIndex("PedidoIndividualId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.PedidoColetivo", b =>
                {
                    b.HasOne("AguiarPay.Business.Models.ComandaColetiva", "ComandaColetiva")
                        .WithOne("PedidoColetivo")
                        .HasForeignKey("AguiarPay.Business.Models.PedidoColetivo", "ComandaColetivaId")
                        .IsRequired();
                });

            modelBuilder.Entity("AguiarPay.Business.Models.PedidoIndividual", b =>
                {
                    b.HasOne("AguiarPay.Business.Models.ComandaIndividual", "ComandaIndividual")
                        .WithOne("PedidoIndividual")
                        .HasForeignKey("AguiarPay.Business.Models.PedidoIndividual", "ComandaIndividualId")
                        .IsRequired();
                });

            modelBuilder.Entity("AguiarPay.Business.Models.Produto", b =>
                {
                    b.HasOne("AguiarPay.Business.Models.PedidoColetivo", "PedidoColetivo")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoColetivoId")
                        .IsRequired();

                    b.HasOne("AguiarPay.Business.Models.PedidoIndividual", "PedidoIndividual")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoIndividualId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
