// <auto-generated />
using System;
using AguiarPay.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AguiarPay.Data.Migrations
{
    [DbContext(typeof(AguiarDbContext))]
    [Migration("20211123193406_AtualizacaoComandasColetivas")]
    partial class AtualizacaoComandasColetivas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AguiarPay.Business.Models.ComandaIndividual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ComandasIndividuais");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.PedidoIndividual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComandaIndividualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComandaIndividualId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidosIndividuais");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("AguiarPay.Business.Models.PedidoIndividual", b =>
                {
                    b.HasOne("AguiarPay.Business.Models.ComandaIndividual", "ComandaIndividual")
                        .WithMany("PedidosIndividuais")
                        .HasForeignKey("ComandaIndividualId")
                        .IsRequired();

                    b.HasOne("AguiarPay.Business.Models.Produto", "Produto")
                        .WithMany("PedidosIndividuais")
                        .HasForeignKey("ProdutoId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
